import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Section from '../components/Section'


export default function Home() {
  return (
    
    <div className={styles.bodysection}>
      <Head>
        <title>Navigation menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <header>
          <div className={styles.logo}>
            Navi.
          </div>
          <div className={styles.nav}>
          </div>
        </header>
        <Section/>
      </div>
    </div>  
      
  )
}
