import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Section from '../components/Section'
import { useState } from "react";
import Link from 'next/link'
import Footer from '../components/Footer'

export default function Home() {
  return (
    
    <div className={styles.bodysection}>
      <Head>
        <title>Navigation menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <header>
          <div className={styles.logo}>
            Navi.
          </div>
          <div className={styles.nav}>
            <nav>
              <ul>
                <li><Link href="#">Documentation</Link></li>
                <li><Link href="#">Navigations</Link></li>
                <li><Link href="#">FAQ</Link></li>
              </ul>
            </nav>
          </div>
        </header>
        <Section/>
        <Footer/> 
      </div>
    </div>  
      
  )
}
